name: Lighthouse CI

on: [push]

jobs:
  lighthouse-test:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build

      - uses: treosh/lighthouse-ci-actions@v2
        with:
          configPath: './lighthouse.json'
          uploadArtifacts: true
